import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Radio Saudade Fm",
            artist: "RadioSaudadeFm",
            cover: "https://img.freepik.com/psd-gratis/maqueta-microfono-escritorio-rectangular-vista-frontal_1332-10597.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://24923.live.streamtheworld.com/SAUDADE_FM_SC",
            active: true,
        },
        {
            name:"Alpha Fm",
            artist: "AlphaFm",
            cover: "https://img.freepik.com/vector-gratis/concepto-marco-neon-aire_52683-52393.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://24083.live.streamtheworld.com/RADIO_ALPHAFM_SC",
            active: false,
        },
        {
            name:"UCP Petropilis",
            artist: "UCPPetropilis",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41309.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://www.ucpfm.com.br/player/getSom.php",
            active: false,
        },
        {
            name:"Rádio BH FM",
            artist: "RádioBHFM",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41314.jpg",
            id: uuidv4(),Rádio BH FM
            color: ["#008781", "#cfc08c"],
            audio: "https://26373.live.streamtheworld.com/BHFM_SC",
            active: false,
        },
        {
            name:"Transamerica pop",
            artist: "Transamericapop",
            cover: "https://img.freepik.com/foto-gratis/fondo-musica-o-podcast-auriculares-taza-cafe-mesa-azul-plana-vista-superior-plana_501050-983.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://24383.live.streamtheworld.com/RT_SP_SC",
            active: false,
        },
        {
            name:"Nova Brasil",
            artist: "NovaBrasil",
            cover: "https://img.freepik.com/vector-gratis/silueta-aparato-radio_23-2147501018.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://26513.live.streamtheworld.com/NOVABRASIL_SP_SC",
            active: false,
        },
        {
            name:"Radio Fm O Dia",
            artist: "RadioFmODia",
            cover: "https://img.freepik.com/vector-gratis/radio-plana-retro-ilustrada_23-2148812864.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://streaming.livespanel.com:20000/live",
            active: false,
        },
        {
            name:"Soul Radio Classic",
            artist: "SoulRadioClassic",
            cover: "https://img.freepik.com/vector-gratis/aire-letrero-neon-marco_23-2148818543.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://listen.soulradioclassics.com/play",
            active: false,
        },
        {   
            name:"Radio Colina",
            artist: "RadioColina",
            cover: "https://img.freepik.com/vector-gratis/fondo-musica_53876-90528.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://paineldj5.com.br:1112/stream/1/",
            active: false,
        },
        {    
            name:"Radio Rfm",
            artist: "RadioRfm",
            cover: "https://img.freepik.com/vector-gratis/dia-mundial-radio-diseno-plano_23-2148802732.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://25653.live.streamtheworld.com/RFM_SC",
            active: false,
        },
        {
            name:"Radio santiago",
            artist: "Radiosantiago",
            cover: "https://img.freepik.com/vector-gratis/marco-neon-vivo-aire_23-2148758076.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://eu6.fastcast4u.com/proxy/dzuigafo?mp=/stream",
            active: false,
        },
        {
            name:"La mega",
            artist: "Lamega",
            cover: "https://img.freepik.com/vector-gratis/texto-plano-dia-mundial-radio_23-2148825802.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://liveaudio.lamusica.com/PR_WMEG_icy",
            active: false,
        },
        {
            name:"kis",
            artist: "kis",
            cover: "https://img.freepik.com/vector-gratis/ilustracion-realista-auriculares-inalambricos_1284-20763.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://rstream.hostdime.com/proxy/kiss949?mp=/8880?ver=825424",
            active: false,
        },
        {
            name:"Rumba",
            artist: "Rumba",
            cover: "https://img.freepik.com/foto-gratis/dispositivo-digital-inalambrico-auriculares-rosa_53876-96804.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://cast20.plugstreaming.com:2020/stream/r981",
            active: false,
        },
        {
            name:"98.9 fm",
            artist: "98.9fm",
            cover: "https://img.freepik.com/vector-gratis/fondo-retro-dia-mundial-radio_23-2147594195.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://live-stream.bimacreative.com.au/",
            active: false,
        },
        {
            name:"Herat radio",
            artist: "Heratradio",
            cover: "https://img.freepik.com/vector-gratis/fondo-onda-ecualizador-colorido_52683-33072.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://media-ice.musicradio.com/HeartLondonMP3",
            active: false,
        },
        {
            name:"RDS radio",
            artist: "RDSradio",
            cover: "https://cdn-icons-png.flaticon.com/512/1251/1251671.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://icstream.rds.radio/rds",
            active: false,
        },
        {
            name:"Swigg Radio",
            artist: "SwiggRadio",
            cover: "https://img.freepik.com/psd-gratis/maqueta-reproductor-multimedia-rose-gold-maqueta-reproductor-multimedia-rose-gold-3d_106244-1745.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://start-adofm.ice.infomaniak.ch/start-adofm-high.mp3",
            active: false,
        },
        {
            name:"Onda latina",
            artist: "Ondalatina",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41311.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://cervera.eldialdigital.com:21131/stream",
            active: false,
        },
        {
            name:"Rock and Pop",
            artist: "RockandPop",
            cover: "https://img.freepik.com/psd-gratis/maqueta-reproductor-multimedia-rose-gold-maqueta-reproductor-multimedia-rose-gold-3d_106244-1745.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://s4.yesstreaming.net:17044/stream/1/",
            active: false,      
         },
    ];
}

export default chillHop;


